### ISSUE TITLE
Add an option to skip the first layer when scanning Docker images

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#346]
## Is your feature request related to a problem? Please describe.

Scanning a Docker image can take a long time because it scans files from all layers, including the first one, which is often the OS image. To mitigate this, ggshield uses a list of directories to skip, but this is not always accurate, especially when scanning Windows-based images.

## Describe the solution you'd like

Assuming the first layer is an OS image provided by an OS vendor, scanning only the files added on top of this first layer would greatly increase scanning speed, without missing secrets.

Add a `--skip-first-layer` option to `secret scan docker`. This option would be off by default to be safe and avoid changing the existing behavior.

**Comment by alaabenfatma** [comment]
Hi @agateau-gg 

Thank you for opening this issue. Here is what I suggest as an enhancement.

## Introduce a whitelist of layers to skip
I suggest creating an extendable whitelist of layers that we can skip after ensuring that they are safe (they contain no leaks).
### How it works
1. We launch ggshield and try to scan a docker image
2. We retrieve the list of the hashes (and the version of the scanning engine used to scan them) of previously scanned images (those we consider safe)
3. For every image layer (extracted from the docker-generated TAR file), we
  1. Check if its hash exists in the whitelist
  2. If it exists, we compare the version of the scanning engine used to determine the _safety_ of the image to the current one
    1. if equal, we skip the layer 
    2. if different scanning engine: we scan the layer. If the layer is still safe, we update the engine's version. If not, we remove the entry from the cache.
    3. if the layer's hash isn't in the whitelist, we scan the layer.
4. If the layer is scanned, and is safe. We append it to the whitelist.
 ```mermaid
graph TB
    A[GGShield] -->|Scan Docker Image| B(Docker Image)
    B --> C{Convert DockerImage to TAR file}
    C --> D{Filter layers}
    D o--o |Refer to this database to filter the layers,based on hash,version couples| E
    E[(Whitelist of layers)]
    D --> F{Is layer whitelisted}
    F --> |YES|G{Is scanning engine version different?}
    G --> |NO|ZZ
    F --> |NO|Y
    G --> |YES|Y{Scan Layer}
    Y --> X{Safe Docker image?}
    X --> |YES - Add to whitelist|E
    ZZ{Skip Layer}
```

### Things to keep in mind
- The whitelist has to be stored persistently. This is important so that we do not lose it on every new CI workflow
