### ISSUE TITLE
Anonymous credentials shouldn't trigger a warning

### ISSUE THREAD

**Issue by tlhackque** [GitGuardian/ggshield#381]
I intentionally added a ftp uri of the form `ftp://anonymous:anonymous @example.com/...`.

This triggered an e-mail telling me to fix a secret leak.

I don't explicitly run GitGuardian, but this came because of a GitHub "pages" commit.  So it may be in that (GitHub-supplied) workflow.

While it's good to warn about the plague of exposed credentials, The FTP anonymous user is well-known (for decades, literally)NOT to be a secret!

a) `ftp://anonymous*@` shouldn't warn.
b) Is there a way to mark any apparent "secret" as not - e.g. a structured comment, or a "ignore this pattern" file I can put in the repo - preferable one level up (like .gitignore)?

**Comment by agateau-gg** [comment]
Hi, thanks for the report.

a) regarding anonymous FTP credentials: you are correct, we are going to update our detector so that these credentials are not reported anymore. This is a server-side change so it won't require a ggshield update.

b) regarding ignoring secrets: there are two ways to ignore a secret.
- Add a `ggignore` comment on the line of the secret
- Mark the secret as ignored in the .gitguardian.yml file

You can learn more about this from [ggshield documentation](https://news.ycombinator.com/item?id=33196662).

**Comment by agateau-gg** [comment]
The detector has been updated, anonymous FTP accounts should no longer be reported as leaks. 

Thanks for the report, closing it now.
