### ISSUE TITLE
Brew installation is very slow

### ISSUE THREAD

**Issue by niosega** [GitGuardian/ggshield#785]
## Environment

- ggshield version: 
- Operating system (Linux, macOS, Windows): Ubuntu & MacOS
- Operating system version: Ubuntu 22.04 / macOS 13
- Python version: 3.11.6 (for both linux and macos)

## Describe the bug

When installing `ggshield` using `brew`, the process is very slow both on linux and macos. It can take up to 20 minutes on some machine. The average is around 4 to 5 minutes.

Steps to reproduce:

1. Remove package if already installed
2. Run command `brew install gitguardian/tap/ggshield`

Of course, I am ready to help you diagnose / improve the process if needed !

**Comment by agateau-gg** [comment]
This is because `brew` rebuilds all dependencies, and that now includes the `cryptography` package, which takes a long time to build.

I don't think there is a way around this when using Homebrew, though I would be happy to be proven wrong.

Using `pipx` to install and update ggshield is faster because `pipx` uses pre-compiled wheels for all ggshield dependencies.

**Comment by agateau-gg** [comment]
Closing this as we can't do much for now.
